### ISSUE TITLE
Feature Request: Disable all DHCP requests

### ISSUE THREAD

**Issue by comminutus** [coreos/coreos-installer#1334]
# Feature Request #
Hello, in our environment we often teardown and recreate our cluster.  This results in several DHCP requests - 1 per node that is being provisioned.  I've already [disabled automatic network configuration](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_disabling_automatic_configuration_of_ethernet_devices) and [use static IP addresses](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/#_configuring_a_static_ip) using NetworkManager, but these modifications occur after the LiveCD is booted.

I've set the `offline: true` value inside of an `install.yaml` file as part of my settings, which gets embedded via `coreos-installer iso ignition embed at `/etc/coreos/installer.d/install.yaml`.  Here's the contents of the file that gets embedded:
```
variant: fcos
version: 1.5.0
storage:
  files:
    - path: /var/roothome/install.ign
      contents:
        local: install.ign

    - path: /etc/coreos/installer.d/install.yaml
      contents:
        local: install.yaml
```
However, despite setting `offline` to `true`, I'm still seeing DHCP requests come through during the LiveCD boot process.  I tried turning off my DHCP server, and the process which requests a DHCP address eventually times out but the installation still succeeds onto the hard disk.

## Desired Feature ##
Have some way to completely disable all network requests / DHCP requests during the LiveCD boot process.
