### ISSUE TITLE
Couldn't reread partition table: device may not support partitions on virtual disk

### ISSUE THREAD

**Issue by Hakujou** [coreos/coreos-installer#163]
# Bug #

## Host Operating System Version ##
VMware ESXi 6.7
## Target Operating System Version ##
FCOS 31.20200127.3.0 stable

## coreos-installer Version ##
31.20200127.3.0 stable

## Expected Behavior ##
When using a VM booting FCOS in PXE with a brand new virtual disk, it should be partitioned properly then the installer should proceed.

## Actual Behavior ##
The disk is getting partitioned (I can see the partition when going into emergency mode) but the installer halt with the following error: ```couldn't reread partition table: device may not support partitions```.

## Reproduction Steps ##
I use the following PXELinux configuration:
```
DEFAULT coreos

LABEL coreos
        MENU default
        KERNEL ../../images/coreos/fedora-coreos-31.20200127.3.0-live-kernel-x86_64
        INITRD ../../images/coreos/fedora-coreos-31.20200127.3.0-live-initramfs.x86_64.img
        APPEND ip=dhcp rd.neednet=1 ignition.firstboot coreos.inst.install_dev=/dev/sda1 ignition.platform.id=vmware coreos.inst.stream=stable ignition.config.url=http://some.web.server/swarm/coreos.ign
```

With the following ignition file:

```
variant: fcos
version: 1.0.0

storage:
  disks:
  - device: /dev/sda
    partitions:
    - label: root
      number: 1
      size_mib: 0
      start_mib: 0
```

## Other Information ##
By the way, is there any way to do a "semi-stateless" installation ? With CoreOS Container Linux, by specifying a root device and preventing Ignition from wiping the partition table, we were able to PXE boot the OS while keeping the hard drive mounted as root (keeping services and docker conf/containers intact), I don't see how to achieve that using FCOS.

Thanks ! :)

**Comment by bgilbert** [comment]
I think you're aware of this, but to be clear: the Ignition config you specified with `ignition.config.url` applies to the boot of the live system, and is not the Ignition config that will be applied to the installed system.  You can specify the latter with `coreos.inst.ignition_url`.

What you're currently doing is partitioning the disk and then trying to install FCOS into a partition.  That doesn't work.  coreos-installer writes a complete disk image, including a partition table.  You can skip your entire Ignition config and specify `coreos.inst.install_dev=/dev/sda` instead of `coreos.inst.install_dev=/dev/sda1`.

Yes, it is possible to do a stateful PXE boot with FCOS.  On Container Linux, `/` is stateful and `/usr` is owned by the OS.  On FCOS the layout is different; `/` is owned by the OS, `/var` is stateful, and configuration is in `/etc`.  So you'd specify an Ignition config which writes config customizations to `/etc` (which is a stateless overlayfs for live PXE boots), and conditionally formats and mounts `/var` for persistent data.  In that case you wouldn't run coreos-installer at all, but would just boot the live image with `ignition.config.url`.

**Comment by Hakujou** [comment]
Thanks a lot, it makes more sense.

A complete list of boot arguments somewhere ? I tried to find it but was unable to, I had to use examples to try things.

Thanks again for this detailled answer, I'll try to mount /var to a persistent storage and see how it goes.

**Comment by Hakujou** [comment]
I'm now using this:

```
DEFAULT coreos

LABEL coreos
        MENU default
        KERNEL ../../images/coreos/fedora-coreos-31.20200127.3.0-live-kernel-x86_64
        INITRD ../../images/coreos/fedora-coreos-31.20200127.3.0-live-initramfs.x86_64.img
        APPEND ip=dhcp rd.neednet=1 ignition.firstboot ignition.platform.id=vmware ignition.config.url=http://web.secure.home.lecat.network/swarm/config-dmz.ign
```

With the following ignition conf:
```
variant: fcos
version: 1.0.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAAB...==

storage:
  disks:
  - device: /dev/sda
    wipe_table: false
    partitions:
    - number: 1
      size_mib: 0
      start_mib: 0
      wipe_partition_entry: true
  filesystems:
    - path: /var
      device: /dev/sda1
      format: xfs
```
It boots fine, but it rejects my public key, so I assume the user isn't properly configured (and likely, the whole ignition conf is ignored). Am I missing something here ?

**Comment by jlebon** [comment]
The list of kargs supported is available here: https://github.com/coreos/coreos-installer#kernel-command-line-options-for-coreos-installer-running-as-a-service

> It boots fine, but it rejects my public key, so I assume the user isn't properly configured (and likely, the whole ignition conf is ignored). Am I missing something here ?

Hmm, do you see Ignition trying to fetch your config in the console?

**Comment by Hakujou** [comment]
It scrolls too fast to see anything, but there's a line in the access log of the web server (code 200) so I assume it's pulling the config file properly.

**Comment by jlebon** [comment]
One thing you can do is follow the instructions at https://github.com/coreos/fedora-coreos-docs/pull/48 to gain access to the node at the console, then inspect the logs. Two services worth looking at are `journalctl -u ignition-fetch` which should show Ignition retrieving the config and `journalctl -u ignition-files` which should show Ignition writing SSH authorized keys.

**Comment by Hakujou** [comment]
I added the init command to kernel args to gain control over the VM.

/var is correctly mounted, but the inside is empty. Considering core home is located at /var/home/core, I assume mounting the directory make it empty, so the OS can't see the SSH pubkey, that's why my connection is denied.
Or maybe the init=/bin/sh kicks in before user home directory is created, but I doubt in considering everything else in ignition config is already provisioned.

Is this an intended behaviour ? That sounds a little bit weird to me.
I'll try to move the passwd part after storage, maybe it'll help (doubt it).

**Comment by Hakujou** [comment]
Moved the passwd part, no changes.
There's only an mnt folder inside /var.

**Comment by jlebon** [comment]
The `init=/bin/sh` trick is just to set a password. It won't have a correctly booted up system. You'll want to reboot and login in order to inspect the node and e.g. journal logs from previous boots.

**Comment by Hakujou** [comment]
Set a password on both root and core users, successfully, however after a reboot, trying to login as either of those users and a password throws "incorrect login", so I guess persistency isn't working properly.

**Comment by jlebon** [comment]
Hmm weird, I just doublechecked that it works here on the same stable release. Are you seeing `avc: denied` messages? Make sure that you've loaded the policy before changing the passwd.

Anyway, back to the actual setup you're trying to accomplish. There are a few things off in the fcct.

> ```
> storage:
>   disks:
>   - device: /dev/sda
>     wipe_table: false
>     partitions:
>     - number: 1
>       size_mib: 0
>       start_mib: 0
>       wipe_partition_entry: true
>   filesystems:
>     - path: /var
>       device: /dev/sda1
>       format: xfs
> ```

First, if you're editing the primary disk, you really want to start adding partitions after 4. Partition 1 for example is the boot partition. We need to document this properly, but you can see the full layout here: https://github.com/coreos/coreos-assembler/blob/60320448f8d191dc73f53baf98e199412ee796f5/src/create_disk.sh#L101. Second, you'll want to also add a systemd mount unit so that `/var` gets mounted on boot. Ignition by default does not take care of that for you.

Check out a complete fcct example at https://github.com/coreos/fedora-coreos-docs/pull/51.

**Comment by Hakujou** [comment]
Using systemd mount for /var was the key here.

Using the following configuration:
```
variant: fcos
version: 1.0.0

passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa AAAA...==

storage:
  disks:
  - device: /dev/sda
    wipe_table: false
    partitions:
      - label: var
        number: 1
  filesystems:
    - path: /var
      device: /dev/disk/by-partlabel/var
      format: xfs
      wipe_filesystem: false
      label: var

systemd:
  units:
    - name: var.mount
      enabled: true
      contents: |
        [Unit]
        Before=local-fs.target
        [Mount]
        Where=/var
        What=/dev/disk/by-partlabel/var
        [Install]
        WantedBy=local-fs.target
```
It seems to work fine !

Huge thanks for the help, I'm closing this issue :)
